// <auto-generated />
using System;
using Interception.UI.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Interception.UI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260314221818_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "btree_gist");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Interception.UI.Domain.Observation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ActionNorm")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("action_norm");

                    b.Property<string>("ActionRaw")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("action_raw");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("created_by");

                    b.Property<short>("DayPart")
                        .HasColumnType("smallint")
                        .HasColumnName("day_part");

                    b.Property<string>("DistrictRaw")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("district_raw");

                    b.Property<string>("Layer")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("layer");

                    b.Property<string>("LocationRaw")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("location_raw");

                    b.Property<string>("Note")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("note");

                    b.Property<Guid?>("ObservationActionId")
                        .HasColumnType("uuid")
                        .HasColumnName("observation_action_id");

                    b.Property<DateOnly>("ObservedDate")
                        .HasColumnType("date")
                        .HasColumnName("observed_date");

                    b.Property<string>("PointRaw")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("point_raw");

                    b.Property<string>("RmRaw")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("rm_raw");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source");

                    b.Property<Guid?>("SourceFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_file_id");

                    b.Property<int?>("SourceRow")
                        .HasColumnType("integer")
                        .HasColumnName("source_row");

                    b.HasKey("Id");

                    b.HasIndex("ActionNorm")
                        .HasDatabaseName("ix_link_observations_action_norm");

                    b.HasIndex("ContentHash")
                        .IsUnique()
                        .HasDatabaseName("ux_link_observations_content_hash");

                    b.HasIndex("ObservationActionId")
                        .HasDatabaseName("ix_link_observations_action_id");

                    b.HasIndex("ObservedDate", "DayPart")
                        .HasDatabaseName("ix_link_observations_date_part");

                    b.HasIndex("SourceFileId", "SourceRow")
                        .HasDatabaseName("ix_link_observations_source_row");

                    b.ToTable("link_observations", null, t =>
                        {
                            t.HasCheckConstraint("ck_link_observations_day_part", "day_part in (1, 2)");
                        });
                });

            modelBuilder.Entity("Interception.UI.Domain.ObservationAction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("description");

                    b.Property<string>("InitiatorRoleName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("initiator_role_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NameNorm")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name_norm");

                    b.Property<string>("ResponderRoleName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("responder_role_name");

                    b.HasKey("Id");

                    b.HasIndex("NameNorm")
                        .IsUnique()
                        .HasDatabaseName("ux_link_observation_actions_name_norm");

                    b.HasIndex("IsActive", "NameNorm")
                        .HasDatabaseName("ix_link_observation_actions_active_name_norm");

                    b.ToTable("link_observation_actions", (string)null);
                });

            modelBuilder.Entity("Interception.UI.Domain.ObservationParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsUnknown")
                        .HasColumnType("boolean")
                        .HasColumnName("is_unknown");

                    b.Property<string>("LabelNorm")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("label_norm");

                    b.Property<string>("LabelRaw")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("label_raw");

                    b.Property<Guid>("ObservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("observation_id");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<string>("RoleRaw")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("role_raw");

                    b.Property<bool>("StartedAsUnknown")
                        .HasColumnType("boolean")
                        .HasColumnName("started_as_unknown");

                    b.HasKey("Id");

                    b.HasIndex("LabelNorm")
                        .HasDatabaseName("ix_link_obs_participants_label_norm");

                    b.HasIndex("ObservationId")
                        .HasDatabaseName("ix_link_obs_participants_observation_id");

                    b.HasIndex("ObservationId", "LabelNorm")
                        .IsUnique()
                        .HasDatabaseName("ux_link_obs_participants_observation_label_norm")
                        .HasFilter("is_unknown = false and label_norm is not null");

                    b.HasIndex("ObservationId", "Ordinal")
                        .IsUnique()
                        .HasDatabaseName("ux_link_obs_participants_observation_ordinal");

                    b.ToTable("link_observation_participants", null, t =>
                        {
                            t.HasCheckConstraint("ck_link_obs_participants_ordinal", "ordinal >= 1");
                        });
                });

            modelBuilder.Entity("Interception.UI.Domain.Observation", b =>
                {
                    b.HasOne("Interception.UI.Domain.ObservationAction", "ObservationAction")
                        .WithMany("Observations")
                        .HasForeignKey("ObservationActionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ObservationAction");
                });

            modelBuilder.Entity("Interception.UI.Domain.ObservationParticipant", b =>
                {
                    b.HasOne("Interception.UI.Domain.Observation", "Observation")
                        .WithMany("Participants")
                        .HasForeignKey("ObservationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Observation");
                });

            modelBuilder.Entity("Interception.UI.Domain.Observation", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("Interception.UI.Domain.ObservationAction", b =>
                {
                    b.Navigation("Observations");
                });
#pragma warning restore 612, 618
        }
    }
}
