// <auto-generated />
using System;
using Interception.UI.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Interception.UI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260320122121_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "btree_gist");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Interception.UI.Domain.Observation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ActionNorm")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("action_norm");

                    b.Property<string>("ActionRaw")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("action_raw");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("created_by");

                    b.Property<string>("DistrictRaw")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("district_raw");

                    b.Property<string>("Layer")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("layer");

                    b.Property<string>("LocationRaw")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("location_raw");

                    b.Property<string>("Note")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("note");

                    b.Property<Guid?>("ObservationActionId")
                        .HasColumnType("uuid")
                        .HasColumnName("observation_action_id");

                    b.Property<DateTime>("ObservedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("observed_date");

                    b.Property<string>("PointRaw")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("point_raw");

                    b.Property<string>("RmRaw")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("rm_raw");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source");

                    b.Property<Guid?>("SourceFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_file_id");

                    b.Property<int?>("SourceRow")
                        .HasColumnType("integer")
                        .HasColumnName("source_row");

                    b.Property<string>("SubdivisionNorm")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("subdivision_norm");

                    b.Property<string>("SubdivisionRaw")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("subdivision_raw");

                    b.Property<short?>("SubdivisionSource")
                        .HasColumnType("smallint")
                        .HasColumnName("subdivision_source");

                    b.Property<short?>("SubdivisionStrength")
                        .HasColumnType("smallint")
                        .HasColumnName("subdivision_strength");

                    b.HasKey("Id");

                    b.HasIndex("ActionNorm")
                        .HasDatabaseName("ix_link_observations_action_norm");

                    b.HasIndex("ContentHash")
                        .IsUnique()
                        .HasDatabaseName("ux_link_observations_content_hash");

                    b.HasIndex("ObservationActionId")
                        .HasDatabaseName("ix_link_observations_observation_action_id");

                    b.HasIndex("ObservedDate")
                        .HasDatabaseName("ix_link_observations_observed_date");

                    b.HasIndex("SubdivisionNorm")
                        .HasDatabaseName("ix_link_observations_subdivision_norm");

                    b.HasIndex("Layer", "RmRaw")
                        .HasDatabaseName("ix_link_observations_layer_rm_raw");

                    b.HasIndex("SourceFileId", "SourceRow")
                        .HasDatabaseName("ix_link_observations_source_row");

                    b.ToTable("link_observations", (string)null);
                });

            modelBuilder.Entity("Interception.UI.Domain.ObservationAction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<short>("Category")
                        .HasColumnType("smallint")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("description");

                    b.Property<string>("InitiatorRoleName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("initiator_role_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NameNorm")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name_norm");

                    b.Property<bool>("RequiresCounterparty")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_counterparty");

                    b.Property<string>("ResponderRoleName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("responder_role_name");

                    b.Property<short?>("TypicalParticipantsCount")
                        .HasColumnType("smallint")
                        .HasColumnName("typical_participants_count");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_link_observation_actions_category");

                    b.HasIndex("NameNorm")
                        .IsUnique()
                        .HasDatabaseName("ux_link_observation_actions_name_norm");

                    b.HasIndex("IsActive", "NameNorm")
                        .HasDatabaseName("ix_link_observation_actions_active_name_norm");

                    b.ToTable("link_observation_actions", null, t =>
                        {
                            t.HasCheckConstraint("ck_link_observation_actions_typical_participants_count", "typical_participants_count is null or typical_participants_count >= 1");
                        });
                });

            modelBuilder.Entity("Interception.UI.Domain.ObservationParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsUnknown")
                        .HasColumnType("boolean")
                        .HasColumnName("is_unknown");

                    b.Property<string>("LabelNorm")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("label_norm");

                    b.Property<string>("LabelRaw")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("label_raw");

                    b.Property<Guid>("ObservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("observation_id");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<string>("RoleRaw")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("role_raw");

                    b.Property<bool>("StartedAsUnknown")
                        .HasColumnType("boolean")
                        .HasColumnName("started_as_unknown");

                    b.HasKey("Id");

                    b.HasIndex("LabelNorm")
                        .HasDatabaseName("ix_link_observation_participants_label_norm");

                    b.HasIndex("ObservationId")
                        .HasDatabaseName("ix_link_observation_participants_observation_id");

                    b.HasIndex("ObservationId", "LabelNorm")
                        .IsUnique()
                        .HasDatabaseName("ux_link_observation_participants_observation_label_norm")
                        .HasFilter("is_unknown = false and label_norm is not null");

                    b.HasIndex("ObservationId", "Ordinal")
                        .IsUnique()
                        .HasDatabaseName("ux_link_observation_participants_observation_ordinal");

                    b.ToTable("link_observation_participants", null, t =>
                        {
                            t.HasCheckConstraint("ck_link_observation_participants_ordinal", "ordinal >= 1");
                        });
                });

            modelBuilder.Entity("Interception.UI.Domain.ObservationProbableAction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("confidence");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("created_by");

                    b.Property<Guid>("ObservationActionId")
                        .HasColumnType("uuid")
                        .HasColumnName("observation_action_id");

                    b.Property<Guid>("ObservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("observation_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("reason");

                    b.Property<short>("Source")
                        .HasColumnType("smallint")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.HasIndex("ObservationActionId")
                        .HasDatabaseName("ix_link_observation_probable_actions_observation_action_id");

                    b.HasIndex("ObservationId")
                        .HasDatabaseName("ix_link_observation_probable_actions_observation_id");

                    b.HasIndex("ObservationId", "ObservationActionId")
                        .IsUnique()
                        .HasDatabaseName("ux_link_observation_probable_actions_observation_action");

                    b.ToTable("link_observation_probable_actions", null, t =>
                        {
                            t.HasCheckConstraint("ck_link_observation_probable_actions_confidence", "confidence >= 0 and confidence <= 1");
                        });
                });

            modelBuilder.Entity("Interception.UI.Domain.ObservationTag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<short>("Kind")
                        .HasColumnType("smallint")
                        .HasColumnName("kind");

                    b.Property<Guid>("ObservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("observation_id");

                    b.Property<string>("RawValue")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("raw_value");

                    b.Property<string>("RawValueNorm")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("raw_value_norm");

                    b.Property<short>("Source")
                        .HasColumnType("smallint")
                        .HasColumnName("source");

                    b.Property<Guid?>("TagCatalogId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_catalog_id");

                    b.HasKey("Id");

                    b.HasIndex("ObservationId")
                        .HasDatabaseName("ix_link_observation_tags_observation_id");

                    b.HasIndex("TagCatalogId")
                        .HasDatabaseName("ix_link_observation_tags_tag_catalog_id");

                    b.HasIndex("Kind", "RawValueNorm")
                        .HasDatabaseName("ix_link_observation_tags_kind_raw_value_norm");

                    b.HasIndex("ObservationId", "Kind", "RawValueNorm")
                        .IsUnique()
                        .HasDatabaseName("ux_link_observation_tags_observation_kind_raw_value_norm");

                    b.ToTable("link_observation_tags", (string)null);
                });

            modelBuilder.Entity("Interception.UI.Domain.ResolvedActor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("created_by");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<string>("DisplayNameNorm")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name_norm");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Note")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("note");

                    b.Property<string>("PrimaryRole")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("primary_role");

                    b.HasKey("Id");

                    b.HasIndex("DisplayNameNorm")
                        .HasDatabaseName("ix_link_resolved_actors_display_name_norm");

                    b.HasIndex("IsActive", "DisplayNameNorm")
                        .HasDatabaseName("ix_link_resolved_actors_active_display_name_norm");

                    b.ToTable("link_resolved_actors", (string)null);
                });

            modelBuilder.Entity("Interception.UI.Domain.ResolvedSubdivision", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LayerHint")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("layer_hint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NameNorm")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name_norm");

                    b.Property<string>("Note")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("note");

                    b.Property<string>("RmHint")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("rm_hint");

                    b.HasKey("Id");

                    b.HasIndex("NameNorm")
                        .HasDatabaseName("ix_link_resolved_subdivisions_name_norm");

                    b.HasIndex("IsActive", "NameNorm")
                        .HasDatabaseName("ix_link_resolved_subdivisions_active_name_norm");

                    b.ToTable("link_resolved_subdivisions", (string)null);
                });

            modelBuilder.Entity("Interception.UI.Domain.TagCatalog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<short>("Kind")
                        .HasColumnType("smallint")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NameNorm")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name_norm");

                    b.HasKey("Id");

                    b.HasIndex("Kind", "NameNorm")
                        .IsUnique()
                        .HasDatabaseName("ux_link_tag_catalog_kind_name_norm");

                    b.HasIndex("IsActive", "Kind", "NameNorm")
                        .HasDatabaseName("ix_link_tag_catalog_active_kind_name_norm");

                    b.ToTable("link_tag_catalog", (string)null);
                });

            modelBuilder.Entity("Interception.UI.Domain.UnknownCluster", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ArchivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("created_by");

                    b.Property<string>("Note")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("note");

                    b.Property<Guid?>("ResolvedActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_actor_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.Property<string>("TitleNorm")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title_norm");

                    b.HasKey("Id");

                    b.HasIndex("ArchivedAtUtc")
                        .HasDatabaseName("ix_link_unknown_clusters_archived_at_utc");

                    b.HasIndex("ResolvedActorId")
                        .HasDatabaseName("ix_link_unknown_clusters_resolved_actor_id");

                    b.HasIndex("TitleNorm")
                        .HasDatabaseName("ix_link_unknown_clusters_title_norm");

                    b.ToTable("link_unknown_clusters", (string)null);
                });

            modelBuilder.Entity("Interception.UI.Domain.UnknownClusterMember", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Note")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("note");

                    b.Property<Guid>("ObservationParticipantId")
                        .HasColumnType("uuid")
                        .HasColumnName("observation_participant_id");

                    b.Property<Guid>("UnknownClusterId")
                        .HasColumnType("uuid")
                        .HasColumnName("unknown_cluster_id");

                    b.HasKey("Id");

                    b.HasIndex("ObservationParticipantId")
                        .IsUnique()
                        .HasDatabaseName("ux_link_unknown_cluster_members_observation_participant_id");

                    b.HasIndex("UnknownClusterId")
                        .HasDatabaseName("ix_link_unknown_cluster_members_unknown_cluster_id");

                    b.HasIndex("UnknownClusterId", "ObservationParticipantId")
                        .IsUnique()
                        .HasDatabaseName("ux_link_unknown_cluster_members_cluster_participant");

                    b.ToTable("link_unknown_cluster_members", (string)null);
                });

            modelBuilder.Entity("Interception.UI.Domain.UnknownSubdivisionCluster", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ArchivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("created_by");

                    b.Property<string>("LabelNorm")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("label_norm");

                    b.Property<string>("LabelRaw")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("label_raw");

                    b.Property<string>("LayerHint")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("layer_hint");

                    b.Property<string>("Note")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("note");

                    b.Property<Guid?>("ResolvedSubdivisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_subdivision_id");

                    b.Property<string>("RmHint")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("rm_hint");

                    b.HasKey("Id");

                    b.HasIndex("ArchivedAtUtc")
                        .HasDatabaseName("ix_link_unknown_subdivision_clusters_archived_at_utc");

                    b.HasIndex("LabelNorm")
                        .HasDatabaseName("ix_link_unknown_subdivision_clusters_label_norm");

                    b.HasIndex("ResolvedSubdivisionId")
                        .HasDatabaseName("ix_link_unknown_subdivision_clusters_resolved_subdivision_id");

                    b.ToTable("link_unknown_subdivision_clusters", (string)null);
                });

            modelBuilder.Entity("Interception.UI.Domain.UnknownSubdivisionObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Note")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("note");

                    b.Property<Guid>("ObservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("observation_id");

                    b.Property<Guid>("UnknownSubdivisionClusterId")
                        .HasColumnType("uuid")
                        .HasColumnName("unknown_subdivision_cluster_id");

                    b.HasKey("Id");

                    b.HasIndex("ObservationId")
                        .HasDatabaseName("ix_link_unknown_subdivision_observations_observation_id");

                    b.HasIndex("UnknownSubdivisionClusterId")
                        .HasDatabaseName("ix_link_unknown_subdivision_observations_cluster_id");

                    b.HasIndex("UnknownSubdivisionClusterId", "ObservationId")
                        .IsUnique()
                        .HasDatabaseName("ux_link_unknown_subdivision_observations_cluster_observation");

                    b.ToTable("link_unknown_subdivision_observations", (string)null);
                });

            modelBuilder.Entity("Interception.UI.Domain.Observation", b =>
                {
                    b.HasOne("Interception.UI.Domain.ObservationAction", "ObservationAction")
                        .WithMany("Observations")
                        .HasForeignKey("ObservationActionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ObservationAction");
                });

            modelBuilder.Entity("Interception.UI.Domain.ObservationParticipant", b =>
                {
                    b.HasOne("Interception.UI.Domain.Observation", "Observation")
                        .WithMany("Participants")
                        .HasForeignKey("ObservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Observation");
                });

            modelBuilder.Entity("Interception.UI.Domain.ObservationProbableAction", b =>
                {
                    b.HasOne("Interception.UI.Domain.ObservationAction", "ObservationAction")
                        .WithMany("ProbableActions")
                        .HasForeignKey("ObservationActionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Interception.UI.Domain.Observation", "Observation")
                        .WithMany("ProbableActions")
                        .HasForeignKey("ObservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Observation");

                    b.Navigation("ObservationAction");
                });

            modelBuilder.Entity("Interception.UI.Domain.ObservationTag", b =>
                {
                    b.HasOne("Interception.UI.Domain.Observation", "Observation")
                        .WithMany("Tags")
                        .HasForeignKey("ObservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Interception.UI.Domain.TagCatalog", "TagCatalog")
                        .WithMany("ObservationTags")
                        .HasForeignKey("TagCatalogId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Observation");

                    b.Navigation("TagCatalog");
                });

            modelBuilder.Entity("Interception.UI.Domain.UnknownCluster", b =>
                {
                    b.HasOne("Interception.UI.Domain.ResolvedActor", "ResolvedActor")
                        .WithMany("ResolvedClusters")
                        .HasForeignKey("ResolvedActorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ResolvedActor");
                });

            modelBuilder.Entity("Interception.UI.Domain.UnknownClusterMember", b =>
                {
                    b.HasOne("Interception.UI.Domain.ObservationParticipant", "ObservationParticipant")
                        .WithMany()
                        .HasForeignKey("ObservationParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Interception.UI.Domain.UnknownCluster", "UnknownCluster")
                        .WithMany("Members")
                        .HasForeignKey("UnknownClusterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ObservationParticipant");

                    b.Navigation("UnknownCluster");
                });

            modelBuilder.Entity("Interception.UI.Domain.UnknownSubdivisionCluster", b =>
                {
                    b.HasOne("Interception.UI.Domain.ResolvedSubdivision", "ResolvedSubdivision")
                        .WithMany("ResolvedClusters")
                        .HasForeignKey("ResolvedSubdivisionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ResolvedSubdivision");
                });

            modelBuilder.Entity("Interception.UI.Domain.UnknownSubdivisionObservation", b =>
                {
                    b.HasOne("Interception.UI.Domain.Observation", "Observation")
                        .WithMany()
                        .HasForeignKey("ObservationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Interception.UI.Domain.UnknownSubdivisionCluster", "UnknownSubdivisionCluster")
                        .WithMany("Observations")
                        .HasForeignKey("UnknownSubdivisionClusterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Observation");

                    b.Navigation("UnknownSubdivisionCluster");
                });

            modelBuilder.Entity("Interception.UI.Domain.Observation", b =>
                {
                    b.Navigation("Participants");

                    b.Navigation("ProbableActions");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Interception.UI.Domain.ObservationAction", b =>
                {
                    b.Navigation("Observations");

                    b.Navigation("ProbableActions");
                });

            modelBuilder.Entity("Interception.UI.Domain.ResolvedActor", b =>
                {
                    b.Navigation("ResolvedClusters");
                });

            modelBuilder.Entity("Interception.UI.Domain.ResolvedSubdivision", b =>
                {
                    b.Navigation("ResolvedClusters");
                });

            modelBuilder.Entity("Interception.UI.Domain.TagCatalog", b =>
                {
                    b.Navigation("ObservationTags");
                });

            modelBuilder.Entity("Interception.UI.Domain.UnknownCluster", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("Interception.UI.Domain.UnknownSubdivisionCluster", b =>
                {
                    b.Navigation("Observations");
                });
#pragma warning restore 612, 618
        }
    }
}
