// <auto-generated />
using System;
using Interception.UI.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Interception.UI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Interception.UI.Domain.CanonicalPerson", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("note");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("DisplayName")
                        .HasDatabaseName("ix_canonical_persons_display_name");

                    b.ToTable("canonical_persons", (string)null);
                });

            modelBuilder.Entity("Interception.UI.Domain.CanonicalPersonMember", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("AddedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("added_at_utc");

                    b.Property<Guid>("CanonicalPersonId")
                        .HasColumnType("TEXT")
                        .HasColumnName("canonical_person_id");

                    b.Property<Guid>("ResolvedParticipantId")
                        .HasColumnType("TEXT")
                        .HasColumnName("resolved_participant_id");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalPersonId")
                        .HasDatabaseName("ix_canonical_person_members_canonical_person_id");

                    b.HasIndex("ResolvedParticipantId")
                        .IsUnique()
                        .HasDatabaseName("ux_canonical_person_members_resolved_participant_id");

                    b.ToTable("canonical_person_members", (string)null);
                });

            modelBuilder.Entity("Interception.UI.Domain.DailyReport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("generated_at");

                    b.Property<string>("GeneratedBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("generated_by");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("published_at");

                    b.Property<DateOnly>("ReportDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("report_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<int>("TotalMessages")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_messages");

                    b.HasKey("Id");

                    b.HasIndex("ReportDate", "Status")
                        .HasDatabaseName("ix_daily_reports_date_status");

                    b.ToTable("daily_reports", (string)null);
                });

            modelBuilder.Entity("Interception.UI.Domain.InterceptionAction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_interception_actions_name");

                    b.ToTable("interception_actions", (string)null);
                });

            modelBuilder.Entity("Interception.UI.Domain.InterceptionMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<string>("Division")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("division");

                    b.Property<string>("Frequency")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("frequency");

                    b.Property<Guid?>("InterceptionActionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("interception_action_id");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("note");

                    b.Property<DateTime>("ObservedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("observed_date");

                    b.Property<string>("PointSignal")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("point_signal");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("VectorSignal")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("vector_signal");

                    b.HasKey("Id");

                    b.HasIndex("Frequency")
                        .HasDatabaseName("ix_interception_messages_frequency");

                    b.HasIndex("InterceptionActionId");

                    b.HasIndex("ObservedDate")
                        .HasDatabaseName("ix_interception_messages_observed_date");

                    b.HasIndex("Frequency", "VectorSignal", "Division")
                        .HasDatabaseName("ix_interception_messages_grouping");

                    b.ToTable("interception_messages", (string)null);
                });

            modelBuilder.Entity("Interception.UI.Domain.InterceptionMessageLabel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("InterceptionMessageId")
                        .HasColumnType("TEXT")
                        .HasColumnName("interception_message_id");

                    b.Property<string>("NameLabel")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("name_label");

                    b.HasKey("Id");

                    b.HasIndex("InterceptionMessageId", "NameLabel")
                        .IsUnique()
                        .HasDatabaseName("ix_labels_message_name");

                    b.ToTable("interception_message_labels", (string)null);
                });

            modelBuilder.Entity("Interception.UI.Domain.InterceptionMessageParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("InterceptionMessageId")
                        .HasColumnType("TEXT")
                        .HasColumnName("interception_message_id");

                    b.Property<bool>("IsUnknown")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_unknown");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ordinal");

                    b.Property<string>("Role")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_participants_name")
                        .HasFilter("name IS NOT NULL");

                    b.HasIndex("InterceptionMessageId", "Ordinal")
                        .IsUnique()
                        .HasDatabaseName("ix_participants_message_ordinal");

                    b.ToTable("interception_message_participants", (string)null);
                });

            modelBuilder.Entity("Interception.UI.Domain.MessageGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CommonDivision")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("common_division");

                    b.Property<string>("CommonFrequency")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("common_frequency");

                    b.Property<string>("CommonVector")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("common_vector");

                    b.Property<Guid>("DailyReportId")
                        .HasColumnType("TEXT")
                        .HasColumnName("daily_report_id");

                    b.Property<string>("GroupKey")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("group_key");

                    b.HasKey("Id");

                    b.HasIndex("DailyReportId")
                        .HasDatabaseName("ix_message_groups_report_id");

                    b.HasIndex("GroupKey")
                        .HasDatabaseName("ix_message_groups_key");

                    b.ToTable("message_groups", (string)null);
                });

            modelBuilder.Entity("Interception.UI.Domain.ParticipantCandidateGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<double>("ConfidenceScore")
                        .HasColumnType("REAL")
                        .HasColumnName("confidence_score");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("resolved_at");

                    b.Property<string>("ResolvedBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("resolved_by");

                    b.Property<Guid?>("ResolvedParticipantId")
                        .HasColumnType("TEXT")
                        .HasColumnName("resolved_participant_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("SuggestedDivision")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("suggested_division");

                    b.Property<string>("SuggestedName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("suggested_name");

                    b.Property<string>("SuggestedRole")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("suggested_role");

                    b.HasKey("Id");

                    b.HasIndex("ConfidenceScore")
                        .HasDatabaseName("ix_candidate_groups_confidence");

                    b.HasIndex("ResolvedParticipantId")
                        .HasDatabaseName("ix_candidate_groups_resolved_participant");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_candidate_groups_status");

                    b.ToTable("participant_candidate_groups", (string)null);
                });

            modelBuilder.Entity("Interception.UI.Domain.ParticipantMatrix", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("DailyReportId")
                        .HasColumnType("TEXT")
                        .HasColumnName("daily_report_id");

                    b.HasKey("Id");

                    b.HasIndex("DailyReportId")
                        .IsUnique();

                    b.ToTable("participant_matrices", (string)null);
                });

            modelBuilder.Entity("Interception.UI.Domain.PersonDirectiveRelation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("comment");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("confidence");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("FromCanonicalPersonId")
                        .HasColumnType("TEXT")
                        .HasColumnName("from_canonical_person_id");

                    b.Property<bool>("IsManual")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_manual");

                    b.Property<string>("RelationType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("relation_type");

                    b.Property<Guid?>("SourceObservationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("source_observation_id");

                    b.Property<Guid>("ToCanonicalPersonId")
                        .HasColumnType("TEXT")
                        .HasColumnName("to_canonical_person_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("FromCanonicalPersonId")
                        .HasDatabaseName("ix_person_directive_relations_from");

                    b.HasIndex("ToCanonicalPersonId")
                        .HasDatabaseName("ix_person_directive_relations_to");

                    b.HasIndex("FromCanonicalPersonId", "ToCanonicalPersonId")
                        .IsUnique()
                        .HasDatabaseName("ix_person_directive_relations_unique_pair");

                    b.ToTable("person_directive_relations", (string)null);
                });

            modelBuilder.Entity("Interception.UI.Domain.ResolvedParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("ConfirmedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("confirmed_at");

                    b.Property<string>("ConfirmedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("confirmed_by");

                    b.Property<string>("Division")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("division");

                    b.Property<string>("Frequency")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("frequency");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Role")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Frequency", "Division")
                        .HasDatabaseName("ix_resolved_participants_name_frequency_division");

                    b.ToTable("resolved_participants", (string)null);
                });

            modelBuilder.Entity("Interception.UI.Domain.Topology.TopologySnapshotBridge", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("BridgeFrequency")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("bridge_frequency");

                    b.Property<string>("ContactPersonName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("contact_person_name");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT")
                        .HasColumnName("group_id");

                    b.Property<string>("PrimaryAction")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("primary_action");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.Property<string>("TargetDivision")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("target_division");

                    b.Property<string>("TargetGroupKey")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("target_group_key");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_topology_snapshot_bridges_group_id");

                    b.HasIndex("GroupId", "TargetGroupKey")
                        .HasDatabaseName("ix_topology_snapshot_bridges_group_target_group");

                    b.ToTable("topology_snapshot_bridges", (string)null);
                });

            modelBuilder.Entity("Interception.UI.Domain.Topology.TopologySnapshotBridgeAction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("BridgeId")
                        .HasColumnType("TEXT")
                        .HasColumnName("bridge_id");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_primary");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("BridgeId")
                        .HasDatabaseName("ix_topology_snapshot_bridge_actions_bridge_id");

                    b.ToTable("topology_snapshot_bridge_actions", (string)null);
                });

            modelBuilder.Entity("Interception.UI.Domain.Topology.TopologySnapshotGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("BridgeWeight")
                        .HasColumnType("INTEGER")
                        .HasColumnName("bridge_weight");

                    b.Property<string>("Division")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("division");

                    b.Property<string>("GroupKey")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("group_key");

                    b.Property<int>("InternalConnectionWeight")
                        .HasColumnType("INTEGER")
                        .HasColumnName("internal_connection_weight");

                    b.Property<string>("KeyPersonName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("key_person_name");

                    b.Property<string>("KeyPersonRole")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("key_person_role");

                    b.Property<int>("MentionCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mention_count");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT")
                        .HasColumnName("run_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("RunId")
                        .HasDatabaseName("ix_topology_snapshot_groups_run_id");

                    b.HasIndex("RunId", "GroupKey")
                        .HasDatabaseName("ix_topology_snapshot_groups_run_group_key");

                    b.ToTable("topology_snapshot_groups", (string)null);
                });

            modelBuilder.Entity("Interception.UI.Domain.Topology.TopologySnapshotGroupAction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT")
                        .HasColumnName("group_id");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_primary");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_topology_snapshot_group_actions_group_id");

                    b.ToTable("topology_snapshot_group_actions", (string)null);
                });

            modelBuilder.Entity("Interception.UI.Domain.Topology.TopologySnapshotGroupFrequency", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("frequency");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT")
                        .HasColumnName("group_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_topology_snapshot_group_frequencies_group_id");

                    b.ToTable("topology_snapshot_group_frequencies", (string)null);
                });

            modelBuilder.Entity("Interception.UI.Domain.Topology.TopologySnapshotGroupMember", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("ConnectionWeight")
                        .HasColumnType("INTEGER")
                        .HasColumnName("connection_weight");

                    b.Property<int>("GroupCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("group_count");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT")
                        .HasColumnName("group_id");

                    b.Property<bool>("IsKeyPerson")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_key_person");

                    b.Property<bool>("IsSharedAcrossGroups")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_shared_across_groups");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_seen_at");

                    b.Property<int>("MentionCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mention_count");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Role")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.Property<int>("UniquePartnerCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("unique_partner_count");

                    b.HasKey("Id");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_topology_snapshot_group_members_group_id");

                    b.ToTable("topology_snapshot_group_members", (string)null);
                });

            modelBuilder.Entity("Interception.UI.Domain.TopologySnapshotRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DateFromUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_from_utc");

                    b.Property<DateTime?>("DateToUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_to_utc");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<int>("GroupCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("group_count");

                    b.Property<bool>("IsStale")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_stale");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CompletedAt")
                        .HasDatabaseName("ix_topology_snapshot_runs_completed_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_topology_snapshot_runs_status");

                    b.HasIndex("DateFromUtc", "DateToUtc", "Status")
                        .HasDatabaseName("ix_topology_snapshot_runs_period_status");

                    b.ToTable("topology_snapshot_runs", (string)null);
                });

            modelBuilder.Entity("Interception.UI.Domain.CanonicalPersonMember", b =>
                {
                    b.HasOne("Interception.UI.Domain.CanonicalPerson", "CanonicalPerson")
                        .WithMany("Members")
                        .HasForeignKey("CanonicalPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Interception.UI.Domain.ResolvedParticipant", "ResolvedParticipant")
                        .WithMany()
                        .HasForeignKey("ResolvedParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CanonicalPerson");

                    b.Navigation("ResolvedParticipant");
                });

            modelBuilder.Entity("Interception.UI.Domain.InterceptionMessage", b =>
                {
                    b.HasOne("Interception.UI.Domain.InterceptionAction", "InterceptionAction")
                        .WithMany()
                        .HasForeignKey("InterceptionActionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("InterceptionAction");
                });

            modelBuilder.Entity("Interception.UI.Domain.InterceptionMessageLabel", b =>
                {
                    b.HasOne("Interception.UI.Domain.InterceptionMessage", null)
                        .WithMany("Labels")
                        .HasForeignKey("InterceptionMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Interception.UI.Domain.InterceptionMessageParticipant", b =>
                {
                    b.HasOne("Interception.UI.Domain.InterceptionMessage", "InterceptionMessage")
                        .WithMany("Participants")
                        .HasForeignKey("InterceptionMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InterceptionMessage");
                });

            modelBuilder.Entity("Interception.UI.Domain.MessageGroup", b =>
                {
                    b.HasOne("Interception.UI.Domain.DailyReport", "DailyReport")
                        .WithMany("Groups")
                        .HasForeignKey("DailyReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Interception.UI.Domain.ValueObjects.MessageGroupEntry", "Entries", b1 =>
                        {
                            b1.Property<Guid>("MessageGroupId")
                                .HasColumnType("TEXT")
                                .HasColumnName("message_group_id");

                            b1.Property<Guid>("MessageId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT")
                                .HasColumnName("message_id");

                            b1.HasKey("MessageGroupId", "MessageId");

                            b1.HasIndex("MessageId")
                                .HasDatabaseName("ix_message_group_entries_message_id");

                            b1.ToTable("message_group_entries", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("MessageGroupId");
                        });

                    b.Navigation("DailyReport");

                    b.Navigation("Entries");
                });

            modelBuilder.Entity("Interception.UI.Domain.ParticipantCandidateGroup", b =>
                {
                    b.HasOne("Interception.UI.Domain.ResolvedParticipant", null)
                        .WithMany()
                        .HasForeignKey("ResolvedParticipantId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsMany("Interception.UI.Domain.ValueObjects.ParticipantRef", "ParticipantRefs", b1 =>
                        {
                            b1.Property<int>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER")
                                .HasColumnName("id");

                            b1.Property<Guid>("CandidateGroupId")
                                .HasColumnType("TEXT")
                                .HasColumnName("candidate_group_id");

                            b1.Property<Guid>("MessageId")
                                .HasColumnType("TEXT")
                                .HasColumnName("message_id");

                            b1.Property<int>("Ordinal")
                                .HasColumnType("INTEGER")
                                .HasColumnName("ordinal");

                            b1.Property<Guid>("ParticipantId")
                                .HasColumnType("TEXT")
                                .HasColumnName("participant_id");

                            b1.HasKey("id");

                            b1.HasIndex("MessageId")
                                .HasDatabaseName("ix_participant_candidate_group_refs_message_id");

                            b1.HasIndex("CandidateGroupId", "ParticipantId")
                                .IsUnique()
                                .HasDatabaseName("ix_participant_candidate_group_refs_group_participant");

                            b1.ToTable("participant_candidate_group_refs", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CandidateGroupId");
                        });

                    b.OwnsOne("Interception.UI.Domain.PatternMatchReasons", "Reasons", b1 =>
                        {
                            b1.Property<Guid>("ParticipantCandidateGroupId")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("CloseInTime")
                                .HasColumnType("INTEGER")
                                .HasColumnName("reason_close_in_time");

                            b1.Property<bool>("SameDivision")
                                .HasColumnType("INTEGER")
                                .HasColumnName("reason_same_division");

                            b1.Property<bool>("SameFrequency")
                                .HasColumnType("INTEGER")
                                .HasColumnName("reason_same_frequency");

                            b1.Property<bool>("SamePointSignal")
                                .HasColumnType("INTEGER")
                                .HasColumnName("reason_same_point_signal");

                            b1.Property<bool>("SameVector")
                                .HasColumnType("INTEGER")
                                .HasColumnName("reason_same_vector");

                            b1.Property<bool>("SharedLabels")
                                .HasColumnType("INTEGER")
                                .HasColumnName("reason_shared_labels");

                            b1.Property<bool>("SharedPartners")
                                .HasColumnType("INTEGER")
                                .HasColumnName("reason_shared_partners");

                            b1.HasKey("ParticipantCandidateGroupId");

                            b1.ToTable("participant_candidate_groups", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ParticipantCandidateGroupId");
                        });

                    b.Navigation("ParticipantRefs");

                    b.Navigation("Reasons")
                        .IsRequired();
                });

            modelBuilder.Entity("Interception.UI.Domain.ParticipantMatrix", b =>
                {
                    b.HasOne("Interception.UI.Domain.DailyReport", "DailyReport")
                        .WithOne("Matrix")
                        .HasForeignKey("Interception.UI.Domain.ParticipantMatrix", "DailyReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Interception.UI.Domain.ValueObjects.MatrixCell", "Cells", b1 =>
                        {
                            b1.Property<Guid>("MatrixId")
                                .HasColumnType("TEXT")
                                .HasColumnName("matrix_id");

                            b1.Property<string>("ParticipantA")
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("participant_a");

                            b1.Property<string>("ParticipantB")
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("participant_b");

                            b1.Property<int>("InteractionCount")
                                .HasColumnType("INTEGER")
                                .HasColumnName("interaction_count");

                            b1.HasKey("MatrixId", "ParticipantA", "ParticipantB");

                            b1.HasIndex("MatrixId", "InteractionCount")
                                .HasDatabaseName("ix_matrix_cells_count");

                            b1.ToTable("matrix_cells", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("MatrixId");
                        });

                    b.Navigation("Cells");

                    b.Navigation("DailyReport");
                });

            modelBuilder.Entity("Interception.UI.Domain.PersonDirectiveRelation", b =>
                {
                    b.HasOne("Interception.UI.Domain.CanonicalPerson", "FromCanonicalPerson")
                        .WithMany()
                        .HasForeignKey("FromCanonicalPersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Interception.UI.Domain.CanonicalPerson", "ToCanonicalPerson")
                        .WithMany()
                        .HasForeignKey("ToCanonicalPersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromCanonicalPerson");

                    b.Navigation("ToCanonicalPerson");
                });

            modelBuilder.Entity("Interception.UI.Domain.Topology.TopologySnapshotBridge", b =>
                {
                    b.HasOne("Interception.UI.Domain.Topology.TopologySnapshotGroup", "Group")
                        .WithMany("Bridges")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Interception.UI.Domain.Topology.TopologySnapshotBridgeAction", b =>
                {
                    b.HasOne("Interception.UI.Domain.Topology.TopologySnapshotBridge", "Bridge")
                        .WithMany("Actions")
                        .HasForeignKey("BridgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bridge");
                });

            modelBuilder.Entity("Interception.UI.Domain.Topology.TopologySnapshotGroup", b =>
                {
                    b.HasOne("Interception.UI.Domain.TopologySnapshotRun", "Run")
                        .WithMany("Groups")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("Interception.UI.Domain.Topology.TopologySnapshotGroupAction", b =>
                {
                    b.HasOne("Interception.UI.Domain.Topology.TopologySnapshotGroup", "Group")
                        .WithMany("Actions")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Interception.UI.Domain.Topology.TopologySnapshotGroupFrequency", b =>
                {
                    b.HasOne("Interception.UI.Domain.Topology.TopologySnapshotGroup", "Group")
                        .WithMany("Frequencies")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Interception.UI.Domain.Topology.TopologySnapshotGroupMember", b =>
                {
                    b.HasOne("Interception.UI.Domain.Topology.TopologySnapshotGroup", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Interception.UI.Domain.CanonicalPerson", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("Interception.UI.Domain.DailyReport", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Matrix");
                });

            modelBuilder.Entity("Interception.UI.Domain.InterceptionMessage", b =>
                {
                    b.Navigation("Labels");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("Interception.UI.Domain.Topology.TopologySnapshotBridge", b =>
                {
                    b.Navigation("Actions");
                });

            modelBuilder.Entity("Interception.UI.Domain.Topology.TopologySnapshotGroup", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Bridges");

                    b.Navigation("Frequencies");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("Interception.UI.Domain.TopologySnapshotRun", b =>
                {
                    b.Navigation("Groups");
                });
#pragma warning restore 612, 618
        }
    }
}
