// <auto-generated />
using System;
using Interception.UI.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Interception.UI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Interception.UI.Domain.DailyReport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("generated_at");

                    b.Property<string>("GeneratedBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("generated_by");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("published_at");

                    b.Property<DateOnly>("ReportDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("report_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<int>("TotalMessages")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_messages");

                    b.HasKey("Id");

                    b.HasIndex("ReportDate", "Status")
                        .HasDatabaseName("ix_daily_reports_date_status");

                    b.ToTable("daily_reports", (string)null);
                });

            modelBuilder.Entity("Interception.UI.Domain.InterceptionAction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_interception_actions_name");

                    b.ToTable("interception_actions", (string)null);
                });

            modelBuilder.Entity("Interception.UI.Domain.InterceptionMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<string>("Division")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("division");

                    b.Property<string>("Frequency")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("frequency");

                    b.Property<Guid?>("InterceptionActionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("interception_action_id");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("note");

                    b.Property<DateTime>("ObservedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("observed_date");

                    b.Property<string>("PointSignal")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("point_signal");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("VectorSignal")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("vector_signal");

                    b.HasKey("Id");

                    b.HasIndex("Frequency")
                        .HasDatabaseName("ix_interception_messages_frequency");

                    b.HasIndex("InterceptionActionId");

                    b.HasIndex("ObservedDate")
                        .HasDatabaseName("ix_interception_messages_observed_date");

                    b.HasIndex("Frequency", "VectorSignal", "Division")
                        .HasDatabaseName("ix_interception_messages_grouping");

                    b.ToTable("interception_messages", (string)null);
                });

            modelBuilder.Entity("Interception.UI.Domain.InterceptionMessageLabel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("InterceptionMessageId")
                        .HasColumnType("TEXT")
                        .HasColumnName("interception_message_id");

                    b.Property<string>("NameLabel")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("name_label");

                    b.HasKey("Id");

                    b.HasIndex("InterceptionMessageId", "NameLabel")
                        .IsUnique()
                        .HasDatabaseName("ix_labels_message_name");

                    b.ToTable("interception_message_labels", (string)null);
                });

            modelBuilder.Entity("Interception.UI.Domain.InterceptionMessageParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("InterceptionMessageId")
                        .HasColumnType("TEXT")
                        .HasColumnName("interception_message_id");

                    b.Property<bool>("IsUnknown")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_unknown");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ordinal");

                    b.Property<string>("Role")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_participants_name")
                        .HasFilter("name IS NOT NULL");

                    b.HasIndex("InterceptionMessageId", "Ordinal")
                        .IsUnique()
                        .HasDatabaseName("ix_participants_message_ordinal");

                    b.ToTable("interception_message_participants", (string)null);
                });

            modelBuilder.Entity("Interception.UI.Domain.MessageGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CommonDivision")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("common_division");

                    b.Property<string>("CommonFrequency")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("common_frequency");

                    b.Property<string>("CommonVector")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("common_vector");

                    b.Property<Guid>("DailyReportId")
                        .HasColumnType("TEXT")
                        .HasColumnName("daily_report_id");

                    b.Property<string>("GroupKey")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("group_key");

                    b.HasKey("Id");

                    b.HasIndex("DailyReportId")
                        .HasDatabaseName("ix_message_groups_report_id");

                    b.HasIndex("GroupKey")
                        .HasDatabaseName("ix_message_groups_key");

                    b.ToTable("message_groups", (string)null);
                });

            modelBuilder.Entity("Interception.UI.Domain.ParticipantCandidateGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<double>("ConfidenceScore")
                        .HasColumnType("REAL")
                        .HasColumnName("confidence_score");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("resolved_at");

                    b.Property<string>("ResolvedBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("resolved_by");

                    b.Property<Guid?>("ResolvedParticipantId")
                        .HasColumnType("TEXT")
                        .HasColumnName("resolved_participant_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("SuggestedDivision")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("suggested_division");

                    b.Property<string>("SuggestedName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("suggested_name");

                    b.Property<string>("SuggestedRole")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("suggested_role");

                    b.HasKey("Id");

                    b.HasIndex("ConfidenceScore")
                        .HasDatabaseName("ix_candidate_groups_confidence");

                    b.HasIndex("ResolvedParticipantId")
                        .HasDatabaseName("ix_candidate_groups_resolved_participant");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_candidate_groups_status");

                    b.ToTable("participant_candidate_groups", (string)null);
                });

            modelBuilder.Entity("Interception.UI.Domain.ParticipantMatrix", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("DailyReportId")
                        .HasColumnType("TEXT")
                        .HasColumnName("daily_report_id");

                    b.HasKey("Id");

                    b.HasIndex("DailyReportId")
                        .IsUnique();

                    b.ToTable("participant_matrices", (string)null);
                });

            modelBuilder.Entity("Interception.UI.Domain.ResolvedParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("ConfirmedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("confirmed_at");

                    b.Property<string>("ConfirmedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("confirmed_by");

                    b.Property<string>("Division")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("division");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Role")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_resolved_participants_name");

                    b.ToTable("resolved_participants", (string)null);
                });

            modelBuilder.Entity("Interception.UI.Domain.InterceptionMessage", b =>
                {
                    b.HasOne("Interception.UI.Domain.InterceptionAction", "InterceptionAction")
                        .WithMany()
                        .HasForeignKey("InterceptionActionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("InterceptionAction");
                });

            modelBuilder.Entity("Interception.UI.Domain.InterceptionMessageLabel", b =>
                {
                    b.HasOne("Interception.UI.Domain.InterceptionMessage", null)
                        .WithMany("Labels")
                        .HasForeignKey("InterceptionMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Interception.UI.Domain.InterceptionMessageParticipant", b =>
                {
                    b.HasOne("Interception.UI.Domain.InterceptionMessage", "InterceptionMessage")
                        .WithMany("Participants")
                        .HasForeignKey("InterceptionMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InterceptionMessage");
                });

            modelBuilder.Entity("Interception.UI.Domain.MessageGroup", b =>
                {
                    b.HasOne("Interception.UI.Domain.DailyReport", "DailyReport")
                        .WithMany("Groups")
                        .HasForeignKey("DailyReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Interception.UI.Domain.Records.MessageGroupEntry", "Entries", b1 =>
                        {
                            b1.Property<Guid>("MessageGroupId")
                                .HasColumnType("TEXT")
                                .HasColumnName("message_group_id");

                            b1.Property<Guid>("MessageId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT")
                                .HasColumnName("message_id");

                            b1.HasKey("MessageGroupId", "MessageId");

                            b1.HasIndex("MessageId")
                                .HasDatabaseName("ix_message_group_entries_message_id");

                            b1.ToTable("message_group_entries", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("MessageGroupId");
                        });

                    b.Navigation("DailyReport");

                    b.Navigation("Entries");
                });

            modelBuilder.Entity("Interception.UI.Domain.ParticipantCandidateGroup", b =>
                {
                    b.HasOne("Interception.UI.Domain.ResolvedParticipant", null)
                        .WithMany()
                        .HasForeignKey("ResolvedParticipantId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsMany("Interception.UI.Domain.Records.ParticipantRef", "ParticipantRefs", b1 =>
                        {
                            b1.Property<int>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER")
                                .HasColumnName("id");

                            b1.Property<Guid>("CandidateGroupId")
                                .HasColumnType("TEXT")
                                .HasColumnName("candidate_group_id");

                            b1.Property<Guid>("MessageId")
                                .HasColumnType("TEXT")
                                .HasColumnName("message_id");

                            b1.Property<int>("Ordinal")
                                .HasColumnType("INTEGER")
                                .HasColumnName("ordinal");

                            b1.Property<Guid>("ParticipantId")
                                .HasColumnType("TEXT")
                                .HasColumnName("participant_id");

                            b1.HasKey("id");

                            b1.HasIndex("MessageId")
                                .HasDatabaseName("ix_participant_candidate_group_refs_message_id");

                            b1.HasIndex("CandidateGroupId", "ParticipantId")
                                .IsUnique()
                                .HasDatabaseName("ix_participant_candidate_group_refs_group_participant");

                            b1.ToTable("participant_candidate_group_refs", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CandidateGroupId");
                        });

                    b.OwnsOne("Interception.UI.Domain.PatternMatchReasons", "Reasons", b1 =>
                        {
                            b1.Property<Guid>("ParticipantCandidateGroupId")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("CloseInTime")
                                .HasColumnType("INTEGER")
                                .HasColumnName("reason_close_in_time");

                            b1.Property<bool>("SameDivision")
                                .HasColumnType("INTEGER")
                                .HasColumnName("reason_same_division");

                            b1.Property<bool>("SameFrequency")
                                .HasColumnType("INTEGER")
                                .HasColumnName("reason_same_frequency");

                            b1.Property<bool>("SamePointSignal")
                                .HasColumnType("INTEGER")
                                .HasColumnName("reason_same_point_signal");

                            b1.Property<bool>("SameVector")
                                .HasColumnType("INTEGER")
                                .HasColumnName("reason_same_vector");

                            b1.Property<bool>("SharedLabels")
                                .HasColumnType("INTEGER")
                                .HasColumnName("reason_shared_labels");

                            b1.Property<bool>("SharedPartners")
                                .HasColumnType("INTEGER")
                                .HasColumnName("reason_shared_partners");

                            b1.HasKey("ParticipantCandidateGroupId");

                            b1.ToTable("participant_candidate_groups");

                            b1.WithOwner()
                                .HasForeignKey("ParticipantCandidateGroupId");
                        });

                    b.Navigation("ParticipantRefs");

                    b.Navigation("Reasons")
                        .IsRequired();
                });

            modelBuilder.Entity("Interception.UI.Domain.ParticipantMatrix", b =>
                {
                    b.HasOne("Interception.UI.Domain.DailyReport", "DailyReport")
                        .WithOne("Matrix")
                        .HasForeignKey("Interception.UI.Domain.ParticipantMatrix", "DailyReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Interception.UI.Domain.Records.MatrixCell", "Cells", b1 =>
                        {
                            b1.Property<Guid>("MatrixId")
                                .HasColumnType("TEXT")
                                .HasColumnName("matrix_id");

                            b1.Property<string>("ParticipantA")
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("participant_a");

                            b1.Property<string>("ParticipantB")
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("participant_b");

                            b1.Property<int>("InteractionCount")
                                .HasColumnType("INTEGER")
                                .HasColumnName("interaction_count");

                            b1.HasKey("MatrixId", "ParticipantA", "ParticipantB");

                            b1.HasIndex("MatrixId", "InteractionCount")
                                .HasDatabaseName("ix_matrix_cells_count");

                            b1.ToTable("matrix_cells", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("MatrixId");
                        });

                    b.Navigation("Cells");

                    b.Navigation("DailyReport");
                });

            modelBuilder.Entity("Interception.UI.Domain.DailyReport", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Matrix");
                });

            modelBuilder.Entity("Interception.UI.Domain.InterceptionMessage", b =>
                {
                    b.Navigation("Labels");

                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
